/**
 * DOCX report renderer using the `docx` library (pure JS, Open XML).
 * Converts a GeneratedReport into a professional Word document buffer.
 */
import type { GeneratedReport } from './index.js';


async function getDocx() {
  try {
    return await import('docx');
  } catch {
    throw new Error(
      'docx is required for DOCX export. Install it: npm install docx --workspace=@geotechcli/core',
    );
  }
}

/**
 * Strip markdown syntax for plain text rendering.
 */
function stripMd(text: string): string {
  return text
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/\*(.+?)\*/g, '$1')
    .replace(/`(.+?)`/g, '$1')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .trim();
}

function isTableSep(line: string): boolean {
  return /^\|[-: |]+\|$/.test(line.trim());
}

function isTableRow(line: string): boolean {
  return line.trim().startsWith('|') && !isTableSep(line);
}

function parseRow(line: string): string[] {
  return line.split('|').slice(1, -1).map(c => c.trim());
}

export async function renderReportAsDocx(report: GeneratedReport): Promise<Buffer> {
  const docx = await getDocx();
  const {
    Document, Packer, Paragraph, TextRun, HeadingLevel,
    Table, TableRow, TableCell, WidthType, BorderStyle,
    AlignmentType, PageBreak, Header, Footer,
  } = docx;

  const BRAND_COLOR = '00b8c8';
  const DARK = '1a1a2e';

  const allChildren: any[] = [];

  // Title
  allChildren.push(
    new Paragraph({
      text: report.title,
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { after: 300 },
      run: { color: BRAND_COLOR },
    }),
  );

  allChildren.push(
    new Paragraph({
      children: [new TextRun({ text: `Generated by geotechCLI v0.3.0 · ${new Date().toISOString().split('T')[0]}`, color: '888899', size: 20 })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 600 },
    }),
  );

  // Sections
  for (const section of report.sections) {
    // Page break before each section (except first)
    if (section !== report.sections[0]) {
      allChildren.push(new Paragraph({ children: [new PageBreak()] }));
    }

    // Section heading
    allChildren.push(
      new Paragraph({
        text: section.title,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 200, after: 180 },
      }),
    );

    // Parse content
    const lines = section.content.split('\n');
    let tableLines: string[] = [];
    let inTable = false;

    const flushTable = () => {
      if (tableLines.length < 2) { tableLines = []; inTable = false; return; }
      const dataLines = tableLines.filter(l => !isTableSep(l));
      if (dataLines.length < 2) { tableLines = []; inTable = false; return; }

      const headers = parseRow(dataLines[0]);
      const rows = dataLines.slice(1).map(parseRow);
      const colCount = headers.length;
      const colWidth = Math.floor(9030 / colCount);

      const headerRow = new TableRow({
        children: headers.map(h =>
          new TableCell({
            children: [new Paragraph({
              children: [new TextRun({ text: stripMd(h), bold: true, color: BRAND_COLOR })],
              alignment: AlignmentType.LEFT,
            })],
            shading: { fill: 'f0f8fa' },
            width: { size: colWidth, type: WidthType.DXA },
          }),
        ),
        tableHeader: true,
      });

      const dataRows = rows.map(row =>
        new TableRow({
          children: row.map(cell =>
            new TableCell({
              children: [new Paragraph({ children: [new TextRun({ text: stripMd(cell), color: DARK })] })],
              width: { size: colWidth, type: WidthType.DXA },
            }),
          ),
        }),
      );

      allChildren.push(
        new Table({
          rows: [headerRow, ...dataRows],
          width: { size: 9030, type: WidthType.DXA },
          borders: {
            top: { style: BorderStyle.SINGLE, size: 1, color: 'ccccdd' },
            bottom: { style: BorderStyle.SINGLE, size: 1, color: 'ccccdd' },
            left: { style: BorderStyle.SINGLE, size: 1, color: 'ccccdd' },
            right: { style: BorderStyle.SINGLE, size: 1, color: 'ccccdd' },
            insideHorizontal: { style: BorderStyle.SINGLE, size: 1, color: 'ccccdd' },
            insideVertical: { style: BorderStyle.SINGLE, size: 1, color: 'ccccdd' },
          },
        }),
      );
      allChildren.push(new Paragraph({ text: '', spacing: { after: 160 } }));
      tableLines = [];
      inTable = false;
    };

    for (const line of lines) {
      if (isTableRow(line) || isTableSep(line)) {
        inTable = true;
        tableLines.push(line);
        continue;
      }
      if (inTable) flushTable();

      const t = line.trim();
      if (!t) { allChildren.push(new Paragraph({ text: '' })); continue; }

      if (/^##\s/.test(t)) {
        allChildren.push(new Paragraph({ text: stripMd(t.replace(/^##\s+/, '')), heading: HeadingLevel.HEADING_2 }));
      } else if (/^###\s/.test(t)) {
        allChildren.push(new Paragraph({ text: stripMd(t.replace(/^###\s+/, '')), heading: HeadingLevel.HEADING_3 }));
      } else if (/^[-*+]\s/.test(t)) {
        allChildren.push(new Paragraph({
          children: [new TextRun({ text: stripMd(t.replace(/^[-*+]\s+/, '')), color: DARK })],
          bullet: { level: 0 },
          spacing: { after: 60 },
        }));
      } else {
        allChildren.push(new Paragraph({
          children: [new TextRun({ text: stripMd(t), color: DARK })],
          spacing: { after: 100 },
        }));
      }
    }
    if (inTable) flushTable();
  }

  const doc = new Document({
    sections: [{
      properties: {},
      headers: {
        default: new Header({
          children: [new Paragraph({
            children: [new TextRun({ text: `geotechCLI  ·  ${report.title}`, color: '888899', size: 18 })],
            alignment: AlignmentType.RIGHT,
          })],
        }),
      },
      footers: {
        default: new Footer({
          children: [new Paragraph({
            children: [new TextRun({ text: 'geotechCLI — Confidential Engineering Report', color: '888899', size: 18 })],
            alignment: AlignmentType.CENTER,
          })],
        }),
      },
      children: allChildren,
    }],
  });

  return Buffer.from(await Packer.toBuffer(doc));
}
