/**
 * PDF report renderer using pdfkit (pure JS, no native deps).
 * Converts a GeneratedReport (markdown sections) to a professional PDF buffer.
 */
import { GEOTECHCLI_VERSION } from '../meta/index.js';
import type { GeneratedReport, ReportSection } from './index.js';


// Dynamic import to avoid top-level require errors when pdfkit is installed
async function getPDFKit() {
  try {
    // @ts-ignore — pdfkit may not have perfect ESM types
    const { default: PDFDocument } = await import('pdfkit');
    return PDFDocument;
  } catch {
    throw new Error(
      'pdfkit is required for PDF export. Install it: npm install pdfkit --workspace=@geotechcli/core',
    );
  }
}

const BRAND_CYAN = '#00b8c8';
const TEXT_DARK = '#1a1a2e';
const TEXT_GRAY = '#555577';
const LINE_GRAY = '#ccccdd';
const PAGE_MARGIN = 56;
const FONT_TITLE = 'Helvetica-Bold';
const FONT_BODY = 'Helvetica';
const FONT_BOLD = 'Helvetica-Bold';

/**
 * Strip markdown syntax for plain text rendering in PDF.
 */
function stripMarkdown(text: string): string {
  return text
    .replace(/^#{1,6}\s+/gm, '')       // headings
    .replace(/\*\*(.+?)\*\*/g, '$1')   // bold
    .replace(/\*(.+?)\*/g, '$1')        // italic
    .replace(/`(.+?)`/g, '$1')          // inline code
    .replace(/^\s*[-*+]\s+/gm, '• ')   // bullets
    .replace(/^\s*\d+\.\s+/gm, '')      // numbered lists
    .replace(/\|[-:| ]+\|/g, '')        // table separators
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1') // links
    .trim();
}

/**
 * Detect if a line is a markdown table row.
 */
function isTableLine(line: string): boolean {
  return line.trim().startsWith('|');
}

/**
 * Parse a simple markdown table into headers and rows.
 */
function parseMarkdownTable(block: string[]): { headers: string[]; rows: string[][] } | null {
  const dataLines = block.filter(l => !l.replace(/\|/g, '').replace(/-/g, '').trim().match(/^[-:| ]*$/));
  if (dataLines.length < 2) return null;
  const parse = (line: string) => line.split('|').slice(1, -1).map(c => c.trim());
  const headers = parse(dataLines[0]);
  const rows = dataLines.slice(1).map(parse);
  return { headers, rows };
}

export async function renderReportAsPdf(report: GeneratedReport): Promise<Buffer> {
  const PDFDocument = await getPDFKit();

  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({ margin: PAGE_MARGIN, size: 'A4' });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const pageWidth = doc.page.width - PAGE_MARGIN * 2;

    // -----------------------------------------------------------------------
    // Title page
    // -----------------------------------------------------------------------
    doc.rect(0, 0, doc.page.width, 8).fill(BRAND_CYAN);
    doc.moveDown(2);

    doc.font(FONT_TITLE).fontSize(22).fillColor(TEXT_DARK)
      .text(report.title, PAGE_MARGIN, 80, { width: pageWidth, align: 'center' });

    doc.moveDown(0.5);
    doc.font(FONT_BODY).fontSize(11).fillColor(TEXT_GRAY)
      .text(`Generated by geotechCLI v${process.env.npm_package_version ?? GEOTECHCLI_VERSION}`, {
        align: 'center',
      });
    doc.font(FONT_BODY).fontSize(10).fillColor(TEXT_GRAY)
      .text(new Date().toISOString().split('T')[0], { align: 'center' });

    doc.moveDown(2);
    doc.moveTo(PAGE_MARGIN, doc.y).lineTo(doc.page.width - PAGE_MARGIN, doc.y)
      .strokeColor(LINE_GRAY).lineWidth(1).stroke();
    doc.moveDown(1.5);

    // Table of contents (section names)
    doc.font(FONT_BOLD).fontSize(12).fillColor(BRAND_CYAN).text('Contents', PAGE_MARGIN);
    doc.moveDown(0.4);
    for (const section of report.sections) {
      doc.font(FONT_BODY).fontSize(10).fillColor(TEXT_DARK)
        .text(`• ${section.title}`, PAGE_MARGIN + 12);
    }

    // -----------------------------------------------------------------------
    // Content sections
    // -----------------------------------------------------------------------
    for (const section of report.sections) {
      doc.addPage();
      doc.rect(0, 0, doc.page.width, 5).fill(BRAND_CYAN);

      doc.moveDown(1);
      doc.font(FONT_TITLE).fontSize(14).fillColor(BRAND_CYAN)
        .text(section.title, PAGE_MARGIN, 40, { width: pageWidth });
      doc.moveDown(0.4);
      doc.moveTo(PAGE_MARGIN, doc.y).lineTo(doc.page.width - PAGE_MARGIN, doc.y)
        .strokeColor(BRAND_CYAN).lineWidth(1.5).stroke();
      doc.moveDown(0.6);

      // Render content line by line
      const lines = section.content.split('\n');
      let tableBuffer: string[] = [];
      let inTable = false;

      const flushTable = () => {
        if (tableBuffer.length === 0) return;
        const parsed = parseMarkdownTable(tableBuffer);
        if (parsed && doc.y < doc.page.height - 120) {
          const colW = pageWidth / parsed.headers.length;
          // Header row
          let x = PAGE_MARGIN;
          doc.font(FONT_BOLD).fontSize(8.5).fillColor(TEXT_DARK);
          for (const h of parsed.headers) {
            doc.text(h, x + 4, doc.y, { width: colW - 8, lineBreak: false });
            x += colW;
          }
          doc.moveDown(0.3);
          doc.moveTo(PAGE_MARGIN, doc.y).lineTo(doc.page.width - PAGE_MARGIN, doc.y)
            .strokeColor(LINE_GRAY).lineWidth(0.5).stroke();
          doc.moveDown(0.2);

          // Data rows
          doc.font(FONT_BODY).fontSize(8.5).fillColor(TEXT_DARK);
          for (const row of parsed.rows) {
            x = PAGE_MARGIN;
            const rowY = doc.y;
            for (const cell of row) {
              doc.text(cell, x + 4, rowY, { width: colW - 8, lineBreak: false });
              x += colW;
            }
            doc.moveDown(0.4);
          }
          doc.moveDown(0.4);
        }
        tableBuffer = [];
        inTable = false;
      };

      for (const line of lines) {
        if (isTableLine(line)) {
          inTable = true;
          tableBuffer.push(line);
          continue;
        }
        if (inTable) flushTable();

        const stripped = strictRenderLine(line, doc, PAGE_MARGIN, pageWidth);
        if (stripped !== null) doc.moveDown(0.3);
      }
      if (inTable) flushTable();
    }

    // -----------------------------------------------------------------------
    // Footer on each page
    // -----------------------------------------------------------------------
    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i);
      doc.font(FONT_BODY).fontSize(8).fillColor(TEXT_GRAY)
        .text(
          `geotechCLI  ·  ${report.title}  ·  Page ${i + 1} of ${range.count}`,
          PAGE_MARGIN,
          doc.page.height - 36,
          { align: 'center', width: pageWidth },
        );
    }

    doc.end();
  });
}

/** Render a single non-table markdown line into the PDF. Returns null if empty line. */
function strictRenderLine(
  line: string,
  doc: any,
  margin: number,
  width: number,
): boolean | null {
  const trimmed = line.trim();
  if (!trimmed) return null;

  if (/^#{1,2}\s/.test(trimmed)) {
    const text = trimmed.replace(/^#{1,2}\s+/, '');
    doc.font('Helvetica-Bold').fontSize(12).fillColor('#00b8c8').text(stripMarkdown(text), margin, undefined, { width });
    return true;
  }
  if (/^#{3,6}\s/.test(trimmed)) {
    const text = trimmed.replace(/^#{3,6}\s+/, '');
    doc.font('Helvetica-Bold').fontSize(10.5).fillColor('#1a1a2e').text(stripMarkdown(text), margin, undefined, { width });
    return true;
  }
  // Bullet
  if (/^[-*+]\s/.test(trimmed)) {
    const text = trimmed.replace(/^[-*+]\s+/, '');
    doc.font('Helvetica').fontSize(10).fillColor('#1a1a2e')
      .text('•  ' + stripMarkdown(text), margin + 10, undefined, { width: width - 10 });
    return true;
  }
  // Normal paragraph
  doc.font('Helvetica').fontSize(10).fillColor('#1a1a2e').text(stripMarkdown(trimmed), margin, undefined, { width });
  return true;
}
