// ---------------------------------------------------------------------------
// Software Bridge — Connect geotechCLI to local geotech software
// Detects running instances, generates automation scripts, exchanges data
// ---------------------------------------------------------------------------

export type SoftwareType = 'plaxis' | 'flac' | 'rocscience';

export interface BridgeStatus {
  software: SoftwareType;
  detected: boolean;
  version?: string;
  host: string;
  port: number;
  error?: string;
}

export interface ScriptTemplate {
  software: SoftwareType;
  language: string;
  description: string;
  script: string;
}

// ---------------------------------------------------------------------------
// Default connection parameters
// ---------------------------------------------------------------------------

const DEFAULT_PORTS: Record<SoftwareType, number> = {
  plaxis: 10000,
  flac: 5000,
  rocscience: 8080,
};

// ---------------------------------------------------------------------------
// Detection (checks if software scripting server is accessible)
// ---------------------------------------------------------------------------

export async function detectSoftware(
  software: SoftwareType,
  host = 'localhost',
  port?: number,
): Promise<BridgeStatus> {
  const targetPort = port ?? DEFAULT_PORTS[software];

  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 3000);

    let url: string;
    if (software === 'plaxis') {
      url = `http://${host}:${targetPort}/`;
    } else if (software === 'flac') {
      url = `http://${host}:${targetPort}/api/v1/status`;
    } else {
      url = `http://${host}:${targetPort}/api/status`;
    }

    const res = await fetch(url, {
      method: 'GET',
      signal: controller.signal,
    }).catch(() => null);

    clearTimeout(timeout);

    if (res && res.ok) {
      return {
        software,
        detected: true,
        host,
        port: targetPort,
        version: 'detected',
      };
    }

    return {
      software,
      detected: false,
      host,
      port: targetPort,
      error: `No response from ${software} at ${host}:${targetPort}`,
    };
  } catch {
    return {
      software,
      detected: false,
      host,
      port: targetPort,
      error: `Cannot reach ${software} scripting server at ${host}:${targetPort}`,
    };
  }
}

// ---------------------------------------------------------------------------
// Script Generation — generate automation scripts for each software
// ---------------------------------------------------------------------------

export function generatePLAXISScript(params: {
  modelType: '2d' | '3d';
  soilLayers?: Array<{ name: string; depth: number; gamma: number; phi: number; cohesion: number }>;
  tunnelDepth?: number;
  tunnelRadius?: number;
}): ScriptTemplate {
  const layers = params.soilLayers ?? [
    { name: 'Fill', depth: 2, gamma: 17, phi: 25, cohesion: 5 },
    { name: 'Clay', depth: 8, gamma: 18, phi: 28, cohesion: 20 },
    { name: 'Sand', depth: 15, gamma: 19, phi: 33, cohesion: 0 },
  ];

  const layerCode = layers.map((l, i) => `
# Layer ${i + 1}: ${l.name}
mat_${i + 1} = g_i.soilmat()
mat_${i + 1}.Identification = "${l.name}"
mat_${i + 1}.SoilModel = "Mohr-Coulomb"
mat_${i + 1}.gammaUnsat = ${l.gamma}
mat_${i + 1}.gammaSat = ${l.gamma + 2}
mat_${i + 1}.cref = ${l.cohesion}
mat_${i + 1}.phi = ${l.phi}
g_i.Soils[${i}].Material = mat_${i + 1}`).join('\n');

  const tunnelCode = params.tunnelDepth ? `
# Tunnel
g_i.tunnel(${params.tunnelDepth}, ${params.tunnelRadius ?? 5})
` : '';

  const script = `# Auto-generated by geotechCLI for PLAXIS ${params.modelType.toUpperCase()}
# Execute in PLAXIS Python scripting console
from plxscripting.easy import new_server

s_i, g_i = new_server('localhost', ${DEFAULT_PORTS.plaxis}, timeout=30)
s_i.new()

# Model geometry
g_i.SoilContour.initializerectangular(-50, 0, 50, -30)
${layerCode}
${tunnelCode}
# Mesh generation
g_i.gotomesh()
g_i.mesh(0.06)  # Fine mesh

# Calculation phases
g_i.gotostages()
g_i.phase(g_i.InitialPhase)
g_i.set(g_i.Phase_1.DeformCalcType, "LoadAdvanced")
g_i.calculate()

# Extract results
print(f"Max displacement: {g_i.getresults(g_i.Phase_1, g_i.ResultTypes.Soil.Utot, 'max'):.4f} m")
print(f"Max stress: {g_i.getresults(g_i.Phase_1, g_i.ResultTypes.Soil.SigmaXXeff, 'min'):.2f} kPa")
`;

  return {
    software: 'plaxis',
    language: 'python',
    description: `PLAXIS ${params.modelType.toUpperCase()} model with ${layers.length} soil layers`,
    script,
  };
}

export function generateFLACScript(params: {
  gridSize?: { x: number; y: number };
  soilProperties?: { name: string; density: number; bulk: number; shear: number; cohesion: number; friction: number };
}): ScriptTemplate {
  const grid = params.gridSize ?? { x: 20, y: 20 };
  const soil = params.soilProperties ?? {
    name: 'Clay', density: 1800, bulk: 2e8, shear: 1e8, cohesion: 20e3, friction: 28,
  };

  const script = `; Auto-generated by geotechCLI for FLAC
; Execute in FLAC command window

model new
model title 'geotechCLI Generated Model'

; Grid
zone create brick size ${grid.x} ${grid.y} 1

; Material: ${soil.name}
zone cmodel assign mohr-coulomb
zone property density ${soil.density} bulk ${soil.bulk} shear ${soil.shear}
zone property cohesion ${soil.cohesion} friction ${soil.friction}

; Boundary conditions
zone face apply velocity-normal 0 range position-x 0
zone face apply velocity-normal 0 range position-x ${grid.x}
zone face apply velocity (0,0,0) range position-z 0

; Gravity
model gravity 0 0 -9.81

; Initial stresses (K0 = 0.5)
zone initialize-stresses ratio 0.5

; Solve
model solve ratio-local 1e-4

; Output
model save 'geotechcli_output.sav'
`;

  return {
    software: 'flac',
    language: 'fish',
    description: `FLAC ${grid.x}×${grid.y} grid with ${soil.name}`,
    script,
  };
}

export function generateRocscienceScript(params: {
  analysisType: 'slope' | 'tunnel' | 'foundation';
  soilLayers?: Array<{ name: string; gamma: number; phi: number; cohesion: number }>;
}): ScriptTemplate {
  const layers = params.soilLayers ?? [
    { name: 'Soil', gamma: 18, phi: 30, cohesion: 10 },
  ];

  const materialDefs = layers.map((l, i) =>
    `mat${i} = model.AddMaterial("${l.name}")
mat${i}.UnitWeight = ${l.gamma}
mat${i}.FrictionAngle = ${l.phi}
mat${i}.Cohesion = ${l.cohesion}`
  ).join('\n');

  const script = `# Auto-generated by geotechCLI for Rocscience RS2/Slide
# Execute in Rocscience scripting console
import rs2

model = rs2.RS2Model()
model.SetTitle("geotechCLI Generated Model")

# Materials
${materialDefs}

# Analysis
model.SetAnalysisType("${params.analysisType}")
model.Compute()

# Results
results = model.GetResults()
print(f"Factor of Safety: {results.GetMinFOS():.3f}")
print(f"Critical surface: {results.GetCriticalSurface()}")
`;

  return {
    software: 'rocscience',
    language: 'python',
    description: `Rocscience ${params.analysisType} analysis`,
    script,
  };
}
