import type {
  FemAnalysisCase,
  FemAssumption,
  FemResultManifest,
  FemVisualizationMesh,
} from './types.js';
import { validateFemAnalysisCase } from './validation.js';

const DEFAULT_UNITS = {
  length: 'm',
  force: 'kN',
  stress: 'kPa',
  density: 'kN/m3',
  displacement: 'mm',
} as const;

function round(value: number, digits = 3): number {
  const factor = 10 ** digits;
  return Math.round(value * factor) / factor;
}

function settlementColor(t: number): [number, number, number] {
  const stops: Array<[number, number, number]> = [
    [43, 62, 154],
    [47, 107, 205],
    [56, 170, 210],
    [80, 200, 120],
    [235, 210, 75],
    [220, 83, 44],
    [170, 25, 55],
  ];
  const scaled = Math.min(Math.max(t, 0), 1) * (stops.length - 1);
  const left = Math.floor(scaled);
  const right = Math.min(left + 1, stops.length - 1);
  const local = scaled - left;
  return [0, 1, 2].map((index) => {
    const value = stops[left][index] + (stops[right][index] - stops[left][index]) * local;
    return round(value / 255, 4);
  }) as [number, number, number];
}

export function buildRaftDemoAnalysisCase(now = new Date('2026-05-16T00:00:00.000Z')): FemAnalysisCase {
  const assumptions: FemAssumption[] = [
    {
      id: 'linear-elastic-screening',
      parameter: 'soil constitutive behavior',
      value: 'linear elastic, drained, small strain',
      basis: 'Experimental offline demonstration for WebGL/FEM workflow validation.',
      confidence: 'review',
      reviewRequired: true,
    },
    {
      id: 'poisson-ratio',
      parameter: 'nu',
      value: 0.3,
      unit: '-',
      basis: 'Typical preliminary drained elastic screening value.',
      confidence: 'review',
      reviewRequired: true,
    },
    {
      id: 'groundwater-not-modelled',
      parameter: 'groundwater',
      value: 'not modelled',
      basis: 'Phase 0 FEM demo excludes pore pressure and consolidation coupling.',
      confidence: 'review',
      reviewRequired: true,
    },
  ];

  return {
    schemaVersion: 'fem-analysis-case.v0',
    caseId: 'raft-settlement-demo',
    title: 'Experimental 3D FEM raft settlement demo',
    createdBy: 'geotechcli-fem-demo',
    createdAt: now.toISOString(),
    experimental: true,
    objective: 'foundation_settlement',
    analysisType: 'static_3d_small_strain',
    units: DEFAULT_UNITS,
    geometry: {
      domain: {
        type: 'box',
        lengthM: 24,
        widthM: 24,
        depthM: 12,
      },
      raft: {
        type: 'raft',
        lengthM: 8,
        widthM: 8,
        thicknessM: 0.6,
        centerXM: 0,
        centerYM: 0,
      },
    },
    materials: [
      {
        id: 'soil-1',
        name: 'Representative elastic soil',
        model: 'linear_elastic',
        elasticModulusKpa: 50000,
        poissonRatio: 0.3,
        unitWeightKnM3: 18,
        evidenceRefs: [],
        assumptions,
      },
    ],
    loads: [
      {
        id: 'raft-pressure',
        type: 'uniform_pressure',
        target: 'raft',
        pressureKpa: 150,
        evidenceRefs: [],
        assumptions: [
          {
            id: 'service-pressure',
            parameter: 'raft service pressure',
            value: 150,
            unit: 'kPa',
            basis: 'Representative load for the experimental demo.',
            confidence: 'review',
            reviewRequired: true,
          },
        ],
      },
    ],
    boundaryConditions: [
      {
        id: 'base-fixed',
        type: 'fixed_base',
        description: 'Base nodes fixed in all translations.',
      },
      {
        id: 'side-rollers',
        type: 'side_rollers',
        description: 'Side boundaries use normal-displacement rollers.',
      },
    ],
    mesh: {
      elementType: 'hex8',
      divisionsX: 12,
      divisionsY: 12,
      divisionsZ: 6,
    },
    groundwater: {
      condition: 'not_modelled',
      note: 'Groundwater and pore-pressure coupling are not included in this experimental demo.',
      reviewRequired: true,
    },
    assumptions,
    evidenceRefs: [],
    limitations: [
      'Experimental screening demo only; not a design model.',
      'Linear elastic small-strain response only.',
      'No plasticity, consolidation, pore-pressure coupling, or construction staging.',
      'Settlement field is generated by a deterministic built-in elastic influence approximation for viewer and workflow validation.',
    ],
  };
}

function buildVisualizationMesh(caseFile: FemAnalysisCase, maxSettlementMm: number): FemVisualizationMesh {
  const { domain, raft } = caseFile.geometry;
  const nx = caseFile.mesh.divisionsX;
  const ny = caseFile.mesh.divisionsY;
  const base: number[] = [];
  const disp: number[] = [];
  const color: number[] = [];
  const tri: number[] = [];
  const edge: number[] = [];
  const sigma = Math.max(raft.lengthM, raft.widthM) * 0.62;

  for (let iy = 0; iy <= ny; iy += 1) {
    const y = -domain.widthM / 2 + (domain.widthM * iy) / ny;
    for (let ix = 0; ix <= nx; ix += 1) {
      const x = -domain.lengthM / 2 + (domain.lengthM * ix) / nx;
      const dx = x - raft.centerXM;
      const dy = y - raft.centerYM;
      const radial = Math.sqrt(dx * dx + dy * dy);
      const edgeBoost = Math.abs(dx) <= raft.lengthM / 2 && Math.abs(dy) <= raft.widthM / 2 ? 1 : 0.88;
      const settlementMm = maxSettlementMm * Math.exp(-(radial * radial) / (2 * sigma * sigma)) * edgeBoost;
      const normalized = settlementMm / maxSettlementMm;
      const [r, g, b] = settlementColor(normalized);
      base.push(round(x), round(y), 0);
      disp.push(0, 0, round(-settlementMm / 1000, 6));
      color.push(r, g, b);
    }
  }

  const idx = (ix: number, iy: number) => iy * (nx + 1) + ix;
  for (let iy = 0; iy < ny; iy += 1) {
    for (let ix = 0; ix < nx; ix += 1) {
      const a = idx(ix, iy);
      const b = idx(ix + 1, iy);
      const c = idx(ix + 1, iy + 1);
      const d = idx(ix, iy + 1);
      tri.push(a, b, c, a, c, d);
    }
  }
  for (let iy = 0; iy <= ny; iy += 1) {
    for (let ix = 0; ix < nx; ix += 1) {
      edge.push(idx(ix, iy), idx(ix + 1, iy));
    }
  }
  for (let ix = 0; ix <= nx; ix += 1) {
    for (let iy = 0; iy < ny; iy += 1) {
      edge.push(idx(ix, iy), idx(ix, iy + 1));
    }
  }

  const z = 0.03;
  const halfL = raft.lengthM / 2;
  const halfW = raft.widthM / 2;
  return {
    base,
    disp,
    color,
    tri,
    edge,
    outlineBase: [
      -halfL, -halfW, z,
      halfL, -halfW, z,
      halfL, halfW, z,
      -halfL, halfW, z,
    ],
    outlineDisp: new Array(12).fill(0),
    outlineIdx: [0, 1, 1, 2, 2, 3, 3, 0],
  };
}

export function runBuiltinElasticRaftDemo(caseFile = buildRaftDemoAnalysisCase()): FemResultManifest {
  const validation = validateFemAnalysisCase(caseFile);
  const material = caseFile.materials[0];
  const load = caseFile.loads[0];
  if (!material || !load) {
    throw new Error('Raft demo requires one material and one pressure load.');
  }
  if (validation.status === 'blocked') {
    throw new Error(`FEM case is blocked: ${validation.findings.map((item) => item.message).join('; ')}`);
  }

  const raft = caseFile.geometry.raft;
  const loadedArea = raft.lengthM * raft.widthM;
  const totalLoadKn = load.pressureKpa * loadedArea;
  const stiffnessSettlementM =
    (load.pressureKpa * Math.min(raft.lengthM, raft.widthM) * (1 - material.poissonRatio ** 2)) /
    material.elasticModulusKpa;
  const maxSettlementMm = round(stiffnessSettlementM * 1000 * 0.82, 3);
  const visualization = buildVisualizationMesh(caseFile, maxSettlementMm);
  const surfaceSettlements = visualization.disp
    .filter((_, index) => index % 3 === 2)
    .map((value) => Math.abs(value * 1000));
  const minSettlementMm = round(Math.min(...surfaceSettlements), 3);

  return {
    schemaVersion: 'fem-result-manifest.v0',
    caseId: caseFile.caseId,
    title: caseFile.title,
    generatedAt: new Date().toISOString(),
    backend: {
      id: 'builtin-elastic3d-demo',
      label: 'Built-in experimental elastic 3D screening demo',
      deterministic: true,
      version: '0.1.0',
    },
    analysisCase: caseFile,
    validation,
    mesh: {
      nodes: (caseFile.mesh.divisionsX + 1) * (caseFile.mesh.divisionsY + 1) * (caseFile.mesh.divisionsZ + 1),
      elements: caseFile.mesh.divisionsX * caseFile.mesh.divisionsY * caseFile.mesh.divisionsZ,
      elementType: caseFile.mesh.elementType,
      divisions: [caseFile.mesh.divisionsX, caseFile.mesh.divisionsY, caseFile.mesh.divisionsZ],
      visualizationNodes: visualization.base.length / 3,
      visualizationTriangles: visualization.tri.length / 3,
      visualizationEdges: visualization.edge.length / 2,
    },
    envelope: {
      maxSettlementMm,
      minSettlementMm,
      totalLoadKn: round(totalLoadKn, 3),
      reactionKn: round(totalLoadKn, 3),
      reactionBalanceRatio: 1,
    },
    visualization,
    assumptions: [
      ...caseFile.assumptions,
      ...caseFile.loads.flatMap((item) => item.assumptions),
    ],
    limitations: caseFile.limitations,
  };
}
