export * from './types.js';
export {
  buildExcavationDemoAnalysisCase,
  buildRaftDemoAnalysisCase,
  buildStagedSettlementConsolidationDemoAnalysisCase,
  buildTunnelVolumeLossDemoAnalysisCase,
  runBuiltinElasticExcavationDemo,
  runBuiltinElasticRaftDemo,
  runBuiltinStagedSettlementConsolidationDemo,
  runBuiltinTunnelVolumeLossDemo,
} from './demo.js';
export { runBuiltinNonlinearConsolidationColumnSolver } from './nonlinear-column-solver.js';
export {
  getFemCapability,
  listFemCapabilities,
  prepareFemAnalysisCaseDraft,
  type FemAnalysisCaseDraft,
  type FemCapability,
  type FemCapabilityStatus,
  type FemRouteObjective,
  type PrepareFemAnalysisCaseDraftInput,
} from './routing.js';
export {
  buildFemDraftCandidateFromReadiness,
  buildFemDraftCandidatesFromGroundModel,
  buildFemDraftInputFromReadiness,
  mapGroundModelEvidenceRefs,
  stripPlaceholderFemValues,
  validateFemGroundModelDraftCandidate,
  validateFemWorkspaceToRunAcceptance,
  type FemGroundModelDraftCandidate,
  type FemGroundModelDraftCandidateValidation,
  type FemGroundModelDraftBridge,
  type FemGroundModelExecutionBoundary,
  type FemWorkspaceToRunAcceptance,
} from './ground-model-draft.js';
export { validateFemAnalysisCase, validateFemResultManifest } from './validation.js';
export {
  validateFemScenarioResult,
  validateFemScenarioSuite,
  type FemScenarioExpectation,
  type FemScenarioMetric,
  type FemScenarioRangeExpectation,
  type FemScenarioRun,
  type FemScenarioSuiteValidation,
  type FemScenarioTrendExpectation,
  type FemScenarioValidation,
} from './scenario-validation.js';
export {
  assessFemProductionReadiness,
  type FemProductionFeature,
  type FemProductionFeatureRequirement,
  type FemProductionReadinessReport,
} from './production-readiness.js';
export {
  DEFAULT_FEM_CONVERGENCE_POLICY,
  evaluateFemTolerance,
  mapMohrCoulombToDruckerPragerTriaxialCompression,
  runDarcySeepage1D,
  runDruckerPragerMaterialPoint,
  runExcavationSupportDesignCheck,
  runFemEngineeringEvidenceSuite,
  runHydroMechanicalCoupling1D,
  runMohrCoulombMaterialPoint,
  runTerzaghiConsolidationTimeStepper,
  terzaghiAverageConsolidation,
  validateFemReviewerApprovalRecord,
  type FemConsolidationStep,
  type FemConsolidationTimeStepperInput,
  type FemConsolidationTimeStepperResult,
  type FemConvergencePolicy,
  type FemDesignCheck,
  type FemDruckerPragerMaterialPointInput,
  type FemDruckerPragerMaterialPointResult,
  type FemDruckerPragerParameterMapping,
  type FemDruckerPragerStressStep,
  type FemEngineeringBenchmarkCase,
  type FemEngineeringEvidenceReport,
  type FemEngineeringKernelFeature,
  type FemExcavationSupportDesignCheckInput,
  type FemExcavationSupportDesignCheckResult,
  type FemHydroMechanicalCouplingInput,
  type FemHydroMechanicalCouplingResult,
  type FemMohrCoulombMaterialPointInput,
  type FemMohrCoulombMaterialPointResult,
  type FemMohrCoulombStressStep,
  type FemPrincipalVector,
  type FemReviewerApprovalRecord,
  type FemReviewerApprovalValidation,
  type FemSeepage1DInput,
  type FemSeepage1DResult,
  type FemSeepageNode,
  type FemSeepageTransientStep,
  type FemToleranceCheck,
} from './engineering-evidence.js';
export { renderFemWebglHtml } from './webgl.js';
export {
  buildPlaneStrainRectangularMesh,
  runPlaneStrainBiotConsolidation,
  runPlaneStrainDruckerPragerLoadSteps,
  runPlaneStrainQuad4Assembly,
  runPlaneStrainSteadySeepage,
  type FemPlaneStrainAssemblyResult,
  type FemPlaneStrainBiotConsolidationModel,
  type FemPlaneStrainBiotConsolidationResult,
  type FemPlaneStrainBiotGaussPointResult,
  type FemPlaneStrainBiotNumericalContract,
  type FemPlaneStrainBiotPressureAudit,
  type FemPlaneStrainBiotStepResult,
  type FemPlaneStrainBoundaryCondition,
  type FemPlaneStrainDruckerPragerGaussPointResult,
  type FemPlaneStrainDruckerPragerResult,
  type FemPlaneStrainDruckerPragerStepResult,
  type FemPlaneStrainGaussPointResult,
  type FemPlaneStrainHydraulicHeadBoundaryCondition,
  type FemPlaneStrainMaterial,
  type FemPlaneStrainModel,
  type FemPlaneStrainNodalFlux,
  type FemPlaneStrainNodalLoad,
  type FemPlaneStrainNode,
  type FemPlaneStrainPorePressureBoundaryCondition,
  type FemPlaneStrainPorePressureNodalFlux,
  type FemPlaneStrainQuad4Element,
  type FemPlaneStrainSeepageGaussPointResult,
  type FemPlaneStrainSeepageModel,
  type FemPlaneStrainSeepageNodeResult,
  type FemPlaneStrainSeepageResult,
} from './plane-strain-assembly.js';
