export * from './types.js';
export {
  buildExcavationDemoAnalysisCase,
  buildRaftDemoAnalysisCase,
  buildSeepageBiotPlaneStrainDemoAnalysisCase,
  buildStagedSettlementConsolidationDemoAnalysisCase,
  buildTunnelVolumeLossDemoAnalysisCase,
  runBuiltinBiotUpPlaneStrainPreview,
  runBuiltinElasticExcavationDemo,
  runBuiltinElasticRaftDemo,
  runBuiltinStagedSettlementConsolidationDemo,
  runBuiltinTunnelVolumeLossDemo,
} from './demo.js';
export { runBuiltinNonlinearConsolidationColumnSolver } from './nonlinear-column-solver.js';
export {
  buildPlaneStrainDruckerPragerAdaptiveExcavationDemoAnalysisCase,
  runBuiltinPlaneStrainDpAdaptivePreview,
  runBuiltinPlaneStrainDpAdaptiveSolver,
  runBuiltinPlaneStrainDruckerPragerAdaptivePreview,
  runBuiltinPlaneStrainDruckerPragerAdaptiveSolver,
} from './nonlinear-plane-strain-solver.js';
export {
  getFemCapability,
  listFemCapabilities,
  prepareFemAnalysisCaseDraft,
  type FemAnalysisCaseDraft,
  type FemCapability,
  type FemCapabilityStatus,
  type FemRouteObjective,
  type PrepareFemAnalysisCaseDraftInput,
} from './routing.js';
export {
  buildFemDraftCandidateFromReadiness,
  buildFemDraftCandidatesFromGroundModel,
  buildFemDraftInputFromReadiness,
  mapGroundModelEvidenceRefs,
  stripPlaceholderFemValues,
  validateFemGroundModelDraftCandidate,
  validateFemWorkspaceToRunAcceptance,
  type FemGroundModelDraftCandidate,
  type FemGroundModelDraftCandidateValidation,
  type FemGroundModelDraftBridge,
  type FemGroundModelExecutionBoundary,
  type FemWorkspaceToRunAcceptance,
} from './ground-model-draft.js';
export { validateFemAnalysisCase, validateFemResultManifest } from './validation.js';
export {
  validateFemScenarioResult,
  validateFemScenarioSuite,
  type FemScenarioExpectation,
  type FemScenarioMetric,
  type FemScenarioRangeExpectation,
  type FemScenarioRun,
  type FemScenarioSuiteValidation,
  type FemScenarioTrendExpectation,
  type FemScenarioValidation,
} from './scenario-validation.js';
export {
  assessFemProductionReadiness,
  type FemProductionFeature,
  type FemProductionFeatureRequirement,
  type FemProductionReadinessReport,
} from './production-readiness.js';
export {
  buildFemExternalBenchmarkAcceptanceContract,
  DEFAULT_FEM_CONVERGENCE_POLICY,
  evaluateFemTolerance,
  mapMohrCoulombToDruckerPragerTriaxialCompression,
  runDarcySeepage1D,
  runDruckerPragerMaterialPoint,
  runExcavationSupportDesignCheck,
  runFemEngineeringEvidenceSuite,
  runHydroMechanicalCoupling1D,
  runMohrCoulombMaterialPoint,
  runTerzaghiConsolidationTimeStepper,
  terzaghiAverageConsolidation,
  validateFemReviewerApprovalRecord,
  type FemConsolidationStep,
  type FemConsolidationTimeStepperInput,
  type FemConsolidationTimeStepperResult,
  type FemConvergencePolicy,
  type FemDesignCheck,
  type FemDruckerPragerMaterialPointInput,
  type FemDruckerPragerMaterialPointResult,
  type FemDruckerPragerParameterMapping,
  type FemDruckerPragerStressStep,
  type FemEngineeringBenchmarkCase,
  type FemEngineeringEvidenceReport,
  type FemEngineeringKernelFeature,
  type FemExternalBenchmarkAcceptanceContract,
  type FemExternalBenchmarkComparisonResult,
  type FemExternalBenchmarkPublishedCitation,
  type FemExternalBenchmarkQuantityRequirement,
  type FemExternalBenchmarkReference,
  type FemExternalBenchmarkReferenceSolverCitation,
  type FemExternalBenchmarkSourceType,
  type FemExternalBenchmarkToleranceType,
  type FemExcavationSupportDesignCheckInput,
  type FemExcavationSupportDesignCheckResult,
  type FemExcavationSupportStageCheck,
  type FemHydroMechanicalCouplingInput,
  type FemHydroMechanicalCouplingResult,
  type FemMohrCoulombMaterialPointInput,
  type FemMohrCoulombMaterialPointResult,
  type FemMohrCoulombStressStep,
  type FemPrincipalVector,
  type FemReviewerApprovalRecord,
  type FemReviewerApprovalValidation,
  type FemSeepage1DInput,
  type FemSeepage1DResult,
  type FemSeepageNode,
  type FemSeepageTransientStep,
  type FemToleranceCheck,
} from './engineering-evidence.js';
export {
  runFemSupportMemberDesignCheck,
  validateFemSupportMemberDesignCheckInput,
  type FemSupportDemandSource,
  type FemSupportDesignFactors,
  type FemSupportDesignReviewMetadata,
  type FemSupportDesignReviewer,
  type FemSupportDesignStatus,
  type FemSupportDesignUnits,
  type FemSupportMemberConvergenceMetadata,
  type FemSupportMemberDemand,
  type FemSupportMemberDesignCheckInput,
  type FemSupportMemberDesignCheckResult,
  type FemSupportMemberDesignInputValidation,
  type FemSupportMemberKind,
  type FemSupportMemberLimitState,
  type FemSupportMemberProperties,
} from './support-design.js';
export { renderFemWebglHtml } from './webgl.js';
export {
  buildCsrFromTriplets,
  csrMatVec,
  solveCsrConjugateGradient,
  type FemCsrConjugateGradientOptions,
  type FemCsrConjugateGradientResult,
  type FemSparseCsrBuildInput,
  type FemSparseCsrMatrix,
  type FemSparseTriplet,
} from './sparse-linear-algebra.js';
export {
  buildPlaneStrainRectangularMesh,
  runPlaneStrainBiotConsolidation,
  runPlaneStrainDruckerPragerBiotPressureReplay,
  runPlaneStrainDruckerPragerLoadSteps,
  runPlaneStrainQuad4Assembly,
  runPlaneStrainSteadySeepage,
  type FemPlaneStrainAssemblyResult,
  type FemPlaneStrainBiotConsolidationModel,
  type FemPlaneStrainBiotConsolidationResult,
  type FemPlaneStrainBiotGaussPointResult,
  type FemPlaneStrainBiotNumericalContract,
  type FemPlaneStrainBiotPressureAudit,
  type FemPlaneStrainBiotPressureDiagnostics,
  type FemPlaneStrainBiotStepResult,
  type FemPlaneStrainBiotTransientAcceptance,
  type FemPlaneStrainBoundaryCondition,
  type FemPlaneStrainDruckerPragerAdaptiveLoadStepAttemptAudit,
  type FemPlaneStrainDruckerPragerAdaptiveLoadSteppingAudit,
  type FemPlaneStrainDruckerPragerBiotPressureReplayAudit,
  type FemPlaneStrainDruckerPragerBiotPressureReplayInput,
  type FemPlaneStrainDruckerPragerBiotPressureReplayResult,
  type FemPlaneStrainDruckerPragerFailure,
  type FemPlaneStrainDruckerPragerGaussPointResult,
  type FemPlaneStrainDruckerPragerHydroMechanicalCouplingAudit,
  type FemPlaneStrainDruckerPragerResidualHistoryEntry,
  type FemPlaneStrainDruckerPragerResult,
  type FemPlaneStrainDruckerPragerSolverOptions,
  type FemPlaneStrainDruckerPragerStepResult,
  type FemPlaneStrainDruckerPragerTerminationReason,
  type FemPlaneStrainGaussPointResult,
  type FemPlaneStrainHydraulicHeadBoundaryCondition,
  type FemPlaneStrainLinearSolverAudit,
  type FemPlaneStrainLinearSolverKind,
  type FemPlaneStrainMaterial,
  type FemPlaneStrainModel,
  type FemPlaneStrainNodalFlux,
  type FemPlaneStrainNodalLoad,
  type FemPlaneStrainNode,
  type FemPlaneStrainPorePressureBoundaryCondition,
  type FemPlaneStrainPorePressureNodalFlux,
  type FemPlaneStrainPrescribedPorePressureIncrement,
  type FemPlaneStrainQuad4Element,
  type FemPlaneStrainSeepageGaussPointResult,
  type FemPlaneStrainSeepageModel,
  type FemPlaneStrainSeepageNodeResult,
  type FemPlaneStrainSeepageResult,
} from './plane-strain-assembly.js';
